name: Docker CI

on:
  push:
    branches:
      - 'main'
    paths:
      - 'main.py'
      - 'Dockerfile'
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/undetected-chromedriver-lambda
          docker build -t ${IMAGE}:${GITHUB_RUN_ID} -t ${IMAGE}:latest .

      - name: Push Docker image
        run: |
          docker push ${IMAGE}:${GITHUB_RUN_ID}
          docker push ${IMAGE}:latest
